### ISSUE TITLE
Please Release Version: 6.7.13

### ISSUE THREAD

**Issue by solomax** [webjars/tempusdominus-bootstrap-4#6]
Would it be possible to release version `6.7.13` (most probably under different maven coordinates :)))

Thanks in advance!

**Comment by jamesward** [comment]
I don't see that release at: https://github.com/tempusdominus/bootstrap-4/tags

Did they move this somewhere else?

**Comment by solomax** [comment]
I guess it is here: https://github.com/Eonasdan/tempus-dominus/tags

sorry, not sure how to create request for new artifact :(

**Comment by jamesward** [comment]
I think that is a different package than this WebJar.  I've deployed that one via NPM WebJars:
```
GroupID = org.webjars.npm
ArtifactID = eonasdan__tempus-dominus
Version = 6.7.13
```

Should be available in the next hour or so on Maven Central.  Let me know if that doesn't work for you.

**Comment by solomax** [comment]
Thanks a lot!
Everything works as expected :)
